name: llmbenchmark
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - lxml
  - arelle-release
  - jupyterlab
  - ipykernel
  - openai
  - pyyaml
  - pip
  - pip:
      - black
      - isort
      - jupyterlab-code-formatter
  - pip:
      - --pre
      - together